[0.098s] Invoking command in '/lab2_ws/build/own_interfaces': CMAKE_PREFIX_PATH=/lab2_ws/install/lab_2:/opt/ros/galactic /usr/bin/cmake /lab2_ws/src/own_interfaces -DCMAKE_INSTALL_PREFIX=/lab2_ws/install/own_interfaces
[0.188s] -- Found rosidl_default_generators: 1.1.1 (/opt/ros/galactic/share/rosidl_default_generators/cmake)
[0.189s] -- Found ament_cmake_core: 1.1.4 (/opt/ros/galactic/share/ament_cmake_core/cmake)
[0.259s] -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
[0.260s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[0.430s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.443s] -- Found rosidl_adapter: 2.2.1 (/opt/ros/galactic/share/rosidl_adapter/cmake)
[0.887s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.023s] -- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
[1.541s] CMake Error at /opt/ros/galactic/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[1.542s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.542s]   own_interfaces --arguments-file
[1.544s]   /lab2_ws/build/own_interfaces/rosidl_adapter__arguments__own_interfaces.json
[1.544s]   --output-dir /lab2_ws/build/own_interfaces/rosidl_adapter/own_interfaces
[1.544s]   --output-file
[1.544s]   /lab2_ws/build/own_interfaces/rosidl_adapter/own_interfaces.idls) returned
[1.544s]   error code 1:
[1.545s] 
[1.545s]   Traceback (most recent call last):
[1.545s] 
[1.545s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1.545s]       return _run_code(code, main_globals, None,
[1.545s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1.545s]       exec(code, run_globals)
[1.546s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.546s]       sys.exit(main())
[1.546s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[1.546s]       abs_idl_file = convert_to_idl(
[1.546s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.546s]       return convert_msg_to_idl(
[1.546s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.547s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.547s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 540, in parse_message_string
[1.547s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[1.547s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 387, in __init__
[1.547s]       self.base_type = BaseType(
[1.547s]     File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
[1.547s]       raise InvalidResourceName(
[1.547s] 
[1.548s]   rosidl_adapter.parser.InvalidResourceName: 'vel' is an invalid message
[1.548s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.548s] 
[1.548s] Call Stack (most recent call first):
[1.548s]   /opt/ros/galactic/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.548s]   CMakeLists.txt:10 (rosidl_generate_interfaces)
[1.548s] 
[1.549s] 
[1.556s] -- Configuring incomplete, errors occurred!
[1.557s] See also "/lab2_ws/build/own_interfaces/CMakeFiles/CMakeOutput.log".
[1.576s] Invoked command in '/lab2_ws/build/own_interfaces' returned '1': CMAKE_PREFIX_PATH=/lab2_ws/install/lab_2:/opt/ros/galactic /usr/bin/cmake /lab2_ws/src/own_interfaces -DCMAKE_INSTALL_PREFIX=/lab2_ws/install/own_interfaces
